blog/urls.py
from django.urls import path
from . import views;

app_name ='blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    #숫자형태의 url이 들어온다.
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),

]

bookmark/urls.py
from django.urls import path
from .views import BookmarkListView, BookmarkCreateView
from .views import BookmarkListView, BookmarkCreateView, BookmarkDetailView,BookmarkUpdateView, BookmarkDeleteView

app_name ='bookmark'

urlpatterns = [
    path('', BookmarkListView.as_view(), name='list'),
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('detail/<int:pk>/', BookmarkDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BookmarkDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"> Django Bookmark </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" datatarget="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" arialabel="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only"></span></a>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'polls:index' %}">Polls <span class="sr-only"></span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'bookmark:list' %}">Bookmark <span class="sr-only"></span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:post_list' %}">Blog <span class="sr-only"></span></a>
            </li>
        </li>
      </ul>
    </div>
  </nav>

  <p></p>
    <div class="row">
      <div class="col">
      {% block content %}
      {% endblock %}
      {% block pagination %}
      <!--페이징 기능-->
      {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>